### ISSUE TITLE
Parse Import Statements Error

### ISSUE THREAD

**Issue by jrhicks** [facebook/esprima#109]
When I run

    require('esprima-fb').parse("import foo from 'bar';")

I get the following error.  Please advise :)

    Error: Line 1: Illegal import declaration
    at throwError (/home/vagrant/RubymineProjects/tcapp/node_modules/esprima-fb/esprima.js:2823:21)
    at throwErrorTolerant (/home/vagrant/RubymineProjects/tcapp/node_modules/esprima-fb/esprima.js:2835:24)
    at parseSourceElement (/home/vagrant/RubymineProjects/tcapp/node_modules/esprima-fb/esprima.js:6431:17)
    at parseProgramElement (/home/vagrant/RubymineProjects/tcapp/node_modules/esprima-fb/esprima.js:6487:16)
    at parseProgramElements (/home/vagrant/RubymineProjects/tcapp/node_modules/esprima-fb/esprima.js:6519:29)
    at parseProgram (/home/vagrant/RubymineProjects/tcapp/node_modules/esprima-fb/esprima.js:6532:16)
    at Object.parse (/home/vagrant/RubymineProjects/tcapp/node_modules/esprima-fb/esprima.js:7709:23)
    at repl:1:24
    at REPLServer.self.eval (repl.js:110:21)
    at Interface.<anonymous> (repl.js:239:12)

```

**Comment by fkling** [comment]
`import` declarations are only allowed in "module" code. By default esprima assumes the code to be "script" code. You can change the mode by passing the an option:

```js
require('esprima-fb').parse("import foo from 'bar';", {sourceType: 'module'})
```

**Comment by jrhicks** [comment]
thanks @fkling
